sudo: required

language: node_js
node_js:
  - 7.2.1

cache:
  yarn: true

script:
  - npm run lint
  - npm run test:cover
  - npm run codacity:coverage

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git config credential.helper "store --file=.git/credentials";
      echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials;
      bash ./.travis.d/tag-version.sh;
    fi
